USE CSCI5408A4;
SET SQL_SAFE_UPDATES = 0;

CREATE VIEW `PERMITCOUNT` AS
    SELECT 
        XLOC, YLOC, COUNT(BP_ID)
    FROM
        building
    GROUP BY XLOC , YLOC;



CREATE VIEW `PERMITTYPECOUNT` AS
    SELECT 
        PERMIT_TYPE, COUNT(BP_ID)
    FROM
        building
    GROUP BY PERMIT_TYPE;

CREATE VIEW `PERMITDATEDIFF` AS
    SELECT 
        (BP_ID),
        DATEDIFF(DATE_OF_PERMIT_ISSUANCE,
                DATE_OF_APPLICATION) AS DATEDIFF
    FROM
        building;

CREATE VIEW `VALUEPROJECT` AS
    SELECT 
        ESTIMATED_VALUE_OF_PROJECT, ALTERNATE_BUILDING_TYPE
    FROM
        building
    WHERE
        ALTERNATE_BUILDING_TYPE <> ' ';


CREATE VIEW `VALUEPROJECTCOUNT` AS
SELECT 
    ESTIMATED_VALUE_OF_PROJECT,ALTERNATE_BUILDING_TYPE,
    COUNT(distinct PERMIT_NUMBER)
FROM
    building B
    WHERE
        ALTERNATE_BUILDING_TYPE <> ' ' 
GROUP BY ESTIMATED_VALUE_OF_PROJECT,ALTERNATE_BUILDING_TYPE;

SELECT 
        AVG (ESTIMATED_VALUE_OF_PROJECT), ALTERNATE_BUILDING_TYPE
    FROM
        building
    WHERE
        ALTERNATE_BUILDING_TYPE <> ' '
        GROUP BY ALTERNATE_BUILDING_TYPE ;

    SELECT 
          AVG (ESTIMATED_VALUE_OF_PROJECT), AVG (ESTIMATED_VALUE_OF_PROJECT),ALTERNATE_BUILDING_TYPE,COMMUNITY
    FROM
        building
    WHERE
       ALTERNATE_BUILDING_TYPE	LIKE '%COMMER%'
       GROUP BY ALTERNATE_BUILDING_TYPE,COMMUNITY ;
       
       
       SELECT 
          AVG (ESTIMATED_VALUE_OF_PROJECT),ALTERNATE_BUILDING_TYPE,COMMUNITY
    FROM
        building
    WHERE
       ALTERNATE_BUILDING_TYPE	LIKE '%COMMER%'
       GROUP BY ALTERNATE_BUILDING_TYPE,COMMUNITY ;